### ISSUE TITLE
Motivation to drop/recreate policy table

### ISSUE THREAD

**Issue by tdeckers** [casbin/cassandra_adapter#2]
What's the motivation behind dropping and recreating the table in this adapter?  Why not just keep the data?
https://github.com/casbin/cassandra-adapter/blob/01749d956862970c0341d53237565f9e9dec298d/adapter.go#L163

**Comment by hsluoyz** [comment]
Because dropping and recreating the policy rules are always simpler than keeping the data. This is the basic mode of Casbin. What you want is called ``AutoSave`` feature (https://github.com/casbin/casbin/wiki/AutoSave). It is an optional feature and only supported by some of the adapters. As far as I know, cassandra-adapter doesn't support it. But PR is welcomed :)

**Comment by hsluoyz** [comment]
Closed as stale.
